development:
  password: shptka_3308501d558face216e01270db085e97
  theme_id: "138816717089"
  store: shopstore-for-brandon.myshopify.com
  # proxy: http://localhost:8080
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json

production:
  password: 16ef663594568325d64408ebcdeef528
  theme_id: "456"
  store: can-i-buy-a-feeling.myshopify.com
  timeout: 60s
  readonly: true
test:
  password: 16ef663594568325d64408ebcdeef528
  theme_id: "789"
  store: can-i-buy-a-feeling.myshopify.com
  ignores: ignore.txt