development:
  password: shptka_33085017896789656575e97
  theme_id: "138819096789789"
  store: your-store.myshopify.com
  # proxy: http://localhost:8080
  ignore_files:
    - "*.gif"
    - "*.jpg"
    - config/settings_data.json
